### ISSUE TITLE
upstream URLs in content not well handled

### ISSUE THREAD

**Issue by old9** [shakyShane/foxy#9]
(user of browser-sync, got the bug and traced it to this module)

say my upstream server `http://localhost:8000` serves a simple html page, with the URL as plain text in the content (not in `href` or so):
```html
<p>http://localhost:8000</p>
```
I proxy this server with:
```javascript
var foxy = require('foxy');
var proxy = foxy('http://localhost:8000').listen(8001);
```
and the proxied version gets malformed:
```html
<p>//localhost:8001%3C/p%3E
```
maybe we need to polish the regexp used here:
https://github.com/shakyShane/foxy/blob/master/lib/utils.js#L79
or do we even need to replace URLs in the content at all?

**Comment by adamnorwood** [comment]
I'm running into the exact same issue via gulp-browser-sync's use of foxy, with over-encoded markup when the proxied URL happens to be in a text node. In my most recent case it was turning this:

```html
<a href="https://law.utexas.dev/calendar/2015/06/24/20471/">https://law.utexas.dev/calendar/2015/06/24/20471/</a></p></div></li></ol></td><td  class="cal-current-month">
```

into:
```html
<a href="//localhost:3000/calendar/2015/06/24/20471/">//localhost:3000/calendar/2015/06/24/20471/%3C/a%3E%3C/p%3E%3C/div%3E%3C/li%3E%3C/ol%3E%3C/td%3E%3Ctd  class="cal-current-month">
```

Yikes! The original markup is already ugly, I know, but it serves as an example where the existing regex keeps on matching until it hits that " in the last element's class name (or at least that's my theory).

It does seem to be a problem with that line of foxy's util.js that @old9 mentions. With the caveat that I'm not a regex expert, adding <> brackets to the lookahead patterns seemed to fix the issue on my end:

```javascript
match: new RegExp("https?://" + string + "(.*?)(?=[ <>,'\"\\s])|('|\")(https?://|/|\\.)?" + string + "(.*?)(?=[ <>,'\"\\s])", "g"),
```

Trying to run regex against HTML is always dicey, but maybe that tweak would help these edge cases if it doesn't introduce any harmful side effects?

**Comment by shakyShane** [comment]
@old9 Thanks for the original report
@adamnorwood Thanks for the details & investigation work. It turns out the regex was being greedy when not inside an attribute https://github.com/shakyShane/foxy/commit/87a912e82897be985e25542b05d908c46bef27fe fixes it.

Yeah, regex + html is always going to be shady, but it's so fast that it's worth the effort, I believe.

**Comment by shakyShane** [comment]
You can both force the latest version of foxy within Browsersync now with

```js
npm rm browser-sync && npm i browser-sync@latest -D
```

**Comment by adamnorwood** [comment]
Wonderful! Thanks for the speedy reply! I can confirm that the fix is working for me now.
